# Generated by Django 3.0.6 on 2020-05-10 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diary', '0005_auto_20200506_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_times', models.IntegerField()),
                ('prefer', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], max_length=10)),
                ('user_friendly', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], max_length=10)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='features',
            name='is_favourite',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Newdiary',
        ),
    ]
