# Generated by Django 3.0.6 on 2020-05-11 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_auto_20200511_0140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='features',
            old_name='content',
            new_name='diarycontent',
        ),
    ]
