# Generated by Django 3.0.6 on 2020-05-12 06:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diary', '0007_auto_20200511_1920'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Features',
            new_name='DiaryEntries',
        ),
    ]
